name: Build & publish Docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build and publish to registry
        uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: Hakimi0804/pyrobud
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
